name: Python Script Workflow

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      
      - name: Run Python script
        run: |
          echo 'word up' >> output.txt

      - name: Commit changes
        run: |
          git config --global user.email "djschoo@protonmail.com"
          git config --global user.name "djschoo"
          git add output.txt
          git commit -m "Add output.txt via GitHub Actions"
          
      - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      force: true