name: Python Script Workflow

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Python script
        run: |
          if [[ ${{ github.event.head_commit.message }} contains "shiny commit" ]]; then
            pip install selenium
            python bcf_scraper.py
          

     # Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          if [[ ${{ github.event.head_commit.message }} contains "shiny commit" ]]; then
            # configure user
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
  
            # stage any file changes to be committed
            git add python_output.txt
  
            # make commit with staged changes
            git commit -m 'python_output.txt created'
  
            # push the commit back up to source GitHub repository
            git push