name: Python Script Workflow

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      
      - name: Run Python script
        run: |
        python printmessage.py
      working-directory: ${{ github.workspace }}  # Specify the directory where the script is located

    - name: Commit changes
      run: |
        
        git add output.txt
        git commit -m "Add output.txt via GitHub Actions"
        git push