name: Python Script Workflow

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2 
      
      - name: Run R script
        run: r rfun.R

     # Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          # configure user
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      
          # stage any file changes to be committed
          git add .
      
          # make commit with staged changes
          git commit -m 'files changed'
      
          # push the commit back up to source GitHub repository
          git push