name: Save Message to File

on:
  push:
    branches:
      - main  # adjust this to your main branch name

jobs:
  run_python_script:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This action checks out your repository's code

    - name: Set up Python
      uses: actions/setup-python@v2  # Sets up Python environment

    - name: Run Python script
      run: |
        python scripts/printmessage.py
      working-directory: ${{ github.workspace }}  # Specify the directory where the script is located

    - name: Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"

        git add output.txt
        git commit -m "Add output.txt via GitHub Actions"
        git push
